import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:elearning_management_app/domain/models/course_model.dart';
import 'package:elearning_management_app/domain/models/semester_model.dart';
import 'package:elearning_management_app/domain/models/validation_result.dart';
import 'package:elearning_management_app/application/controllers/course/course_instructor_provider.dart';
import 'package:elearning_management_app/application/controllers/semester/semester_provider.dart';

// Using global semester providers from semester_provider.dart

class CreateCoursePage extends ConsumerStatefulWidget {
  final VoidCallback? onSuccess;
  final VoidCallback? onCancel;

  const CreateCoursePage({
    super.key,
    this.onSuccess,
    this.onCancel,
  });

  @override
  ConsumerState<CreateCoursePage> createState() => _CreateCoursePageState();
}

class _CreateCoursePageState extends ConsumerState<CreateCoursePage> {
  final TextEditingController _courseCodeController = TextEditingController();
  final TextEditingController _courseNameController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();

  final _formKey = GlobalKey<FormState>();
  // Removed direct repository access - use provider instead
  final TextEditingController _semesterController = TextEditingController();
  final TextEditingController _sessionsController =
      TextEditingController(text: '10');

  bool isLoading = false;
  // Removed _semestersLoading - using provider loading state

  String? _selectedSemester;
  // Removed local semester lists - using provider instead

  // Form validation states
  String? _courseCodeError;
  String? _courseNameError;
  String? _semesterError;
  String? _sessionsError;
  String? _descriptionError;

  @override
  void initState() {
    super.initState();
    // Semester loading handled by provider
  }

  // Removed _loadSemesters - using provider directly in UI

  // Removed _filterSemesters - not needed with DropdownMenu's built-in filtering

  // Basic form validation - only check if required fields are empty
  bool _validateBasicForm() {
    bool isValid = true;

    // Validate course code
    if (_courseCodeController.text.trim().isEmpty) {
      setState(() => _courseCodeError = 'Please enter course code');
      isValid = false;
    }

    // Validate course name
    if (_courseNameController.text.trim().isEmpty) {
      setState(() => _courseNameError = 'Please enter course name');
      isValid = false;
    }

    // Validate semester selection
    if (_selectedSemester == null || _selectedSemester!.isEmpty) {
      setState(() => _semesterError = 'Please select semester');
      isValid = false;
    }

    // Validate sessions - only check if empty and if it's a valid number
    final sessionsText = _sessionsController.text.trim();
    if (sessionsText.isEmpty) {
      setState(() => _sessionsError = 'Please enter number of sessions');
      isValid = false;
    } else {
      final sessions = int.tryParse(sessionsText);
      if (sessions == null) {
        setState(() => _sessionsError = 'Please enter a valid number');
        isValid = false;
      }
    }

    return isValid;
  }

  // Removed old validation method - business rules moved to Controller layer

  Future<void> _createCourse() async {
    // Clear previous errors
    setState(() {
      _courseCodeError = null;
      _courseNameError = null;
      _semesterError = null;
      _sessionsError = null;
      _descriptionError = null;
    });

    // Basic UI validation (only check if fields are empty)
    if (!_validateBasicForm()) {
      return;
    }

    setState(() => isLoading = true);

    try {
      final course = CourseModel(
        id: '', // Will be generated by Firestore
        code: _courseCodeController.text.trim(),
        name: _courseNameController.text.trim(),
        instructor: '', // Will be set by repository
        semester: _selectedSemester!,
        sessions: int.parse(_sessionsController.text.trim()),
        description: _descriptionController.text.trim(),
        status: 'active', // Always active for new courses
      );

      // Create course using provider - now returns ValidationResult
      final notifier = ref.read(courseInstructorProvider.notifier);
      final result = await notifier.createCourse(course);

      if (result.isSuccess) {
        // Auto-refresh course list
        ref.invalidate(courseInstructorProvider);

        if (mounted) {
          _showSuccess(
            '✅ Course created successfully!\n'
            'Code: ${_courseCodeController.text}\n'
            'Name: ${_courseNameController.text}',
          );

          await Future.delayed(const Duration(seconds: 1));
          if (mounted && widget.onSuccess != null) {
            widget.onSuccess!();
          }
        }
      } else {
        // Handle validation errors - display specific field errors
        if (result.fieldError != null) {
          setState(() {
            switch (result.fieldError) {
              case 'courseCode':
                _courseCodeError = result.message;
                break;
              case 'courseName':
                _courseNameError = result.message;
                break;
              case 'semester':
                _semesterError = result.message;
                break;
              case 'sessions':
                _sessionsError = result.message;
                break;
              case 'description':
                _descriptionError = result.message;
                break;
              default:
                // General error - show as snackbar
                _showError('❌ ${result.message}');
            }
          });
        } else {
          // General error - show as snackbar
          _showError('❌ ${result.message}');
        }
      }
    } catch (e) {
      _showError('❌ An unexpected error occurred: ${e.toString()}');
    } finally {
      setState(() => isLoading = false);
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red,
      ),
    );
  }

  void _showSuccess(String message) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF1F2937),
        title: const Row(
          children: [
            Icon(Icons.check_circle, color: Colors.green, size: 32),
            SizedBox(width: 12),
            Text(
              '🎉 Success!',
              style: TextStyle(color: Colors.white),
            ),
          ],
        ),
        content: Text(
          message,
          style: const TextStyle(color: Colors.white70),
        ),
        actions: [
          ElevatedButton(
            onPressed: () {
              Navigator.pop(context);
              if (widget.onSuccess != null) {
                widget.onSuccess!();
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.green,
              foregroundColor: Colors.white,
            ),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }

  void _handleCancel() {
    if (widget.onCancel != null) {
      widget.onCancel!();
    }
  }

  Widget _buildSection(String title, List<Widget> children) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 16.0),
          child: Text(
            title,
            style: const TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Colors.blue,
            ),
          ),
        ),
        ...children,
      ],
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    TextInputType keyboardType = TextInputType.text,
    int minLines = 1,
    int? maxLines,
    String? Function(String?)? validator,
    String? errorText,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16.0),
      child: TextFormField(
        controller: controller,
        keyboardType: keyboardType,
        minLines: minLines,
        maxLines: maxLines ?? minLines,
        style: const TextStyle(color: Colors.white),
        decoration: InputDecoration(
          labelText: label,
          labelStyle: const TextStyle(color: Colors.grey),
          hintText: hint,
          hintStyle: const TextStyle(color: Colors.grey),
          errorText: errorText,
          errorStyle: const TextStyle(color: Colors.red),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide(color: Colors.grey[700]!),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Colors.indigo, width: 2),
          ),
          filled: true,
          fillColor: Colors.grey[900],
        ),
        validator: validator,
      ),
    );
  }

  Widget _buildSemesterDropdownMenu() {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16.0),
      child: Consumer(
        builder: (context, ref, child) {
          final semestersAsync = ref.watch(semesterListProvider);

          return semestersAsync.when(
            data: (semesters) => LayoutBuilder(
              builder: (context, constraints) {
                return DropdownMenu<String>(
                  controller: _semesterController,
                  width: constraints.maxWidth, // Fix width to match parent
                  label: const Text('Semester'),
                  hintText: 'Select semester...',
                  enableFilter: true,
                  requestFocusOnTap: true,
                  errorText: _semesterError,
                  textStyle: const TextStyle(color: Colors.white),
                  inputDecorationTheme: InputDecorationTheme(
                    labelStyle: const TextStyle(color: Colors.grey),
                    hintStyle: const TextStyle(color: Colors.grey),
                    errorStyle: const TextStyle(color: Colors.red),
                    filled: true,
                    fillColor: Colors.grey[900],
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: BorderSide(color: Colors.grey[700]!),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: BorderSide(color: Colors.grey[700]!),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: const BorderSide(color: Colors.indigo),
                    ),
                    errorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: const BorderSide(color: Colors.red),
                    ),
                    focusedErrorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: const BorderSide(color: Colors.red),
                    ),
                  ),
                  menuHeight: semesters.length <= 3
                      ? semesters.length * 48.0 +
                          16 // Dynamic height for <= 3 items
                      : 160.0, // Fixed height for > 3 items with scroll
                  menuStyle: MenuStyle(
                    backgroundColor: WidgetStateProperty.all(Colors.grey[900]!),
                    surfaceTintColor:
                        WidgetStateProperty.all(Colors.transparent),
                    shape: WidgetStateProperty.all(RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    )),
                  ),
                  onSelected: (String? value) {
                    if (value != null) {
                      setState(() {
                        _selectedSemester = value;
                        _semesterError =
                            null; // Clear error when selection is made
                      });
                    }
                  },
                  dropdownMenuEntries: semesters.map<DropdownMenuEntry<String>>(
                    (SemesterModel semester) {
                      return DropdownMenuEntry<String>(
                        value: semester.name,
                        label: semester.name, // Only show name, no description
                        style: MenuItemButton.styleFrom(
                          foregroundColor: Colors.white,
                          backgroundColor: Colors.grey[900],
                        ),
                      );
                    },
                  ).toList(),
                );
              },
            ),
            loading: () => const Center(
              child: CircularProgressIndicator(
                strokeWidth: 2,
                valueColor: AlwaysStoppedAnimation(Colors.indigo),
              ),
            ),
            error: (error, stack) => Text(
              'Error loading semesters: $error',
              style: const TextStyle(color: Colors.red),
            ),
          );
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF111827),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey[800]!),
      ),
      child: isLoading
          ? const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(color: Colors.indigo),
                  SizedBox(height: 16),
                  Text(
                    '🔄 Creating course...',
                    style: TextStyle(color: Colors.white70),
                  ),
                ],
              ),
            )
          : SingleChildScrollView(
              padding: const EdgeInsets.all(24.0),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    /// 📌 NOTE AT TOP
                    Container(
                      padding: const EdgeInsets.all(16),
                      margin: const EdgeInsets.only(bottom: 16),
                      decoration: BoxDecoration(
                        color: Colors.blue[900]?.withValues(alpha: 0.3),
                        border: Border.all(color: Colors.blue[700]!),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: const Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'ℹ️ Note:',
                            style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 14,
                              color: Colors.blue,
                            ),
                          ),
                          SizedBox(height: 8),
                          Text(
                            '• Course code must be unique\n'
                            '• Course name is required\n'
                            '• Select appropriate semester\n'
                            '• Set maximum capacity for enrollments',
                            style: TextStyle(
                              fontSize: 12,
                              color: Colors.white70,
                            ),
                          ),
                        ],
                      ),
                    ),

                    _buildSection(
                      '📚 Basic Information',
                      [
                        _buildTextField(
                          controller: _courseCodeController,
                          label: 'Course Code',
                          hint: 'E.g.: CS101',
                          errorText: _courseCodeError,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Please enter course code';
                            }
                            if (value.length < 3) {
                              return 'Course code must be at least 3 characters';
                            }
                            return null;
                          },
                        ),
                        _buildTextField(
                          controller: _courseNameController,
                          label: 'Course Name',
                          hint: 'E.g.: Introduction to Programming',
                          errorText: _courseNameError,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Please enter course name';
                            }
                            if (value.length < 5) {
                              return 'Course name must be at least 5 characters';
                            }
                            return null;
                          },
                        ),
                        _buildTextField(
                          controller: _descriptionController,
                          label: 'Description',
                          hint: 'Brief description of the course...',
                          minLines: 3,
                          maxLines: 5,
                          errorText: _descriptionError,
                        ),
                      ],
                    ),

                    _buildSection(
                      '⚙️ Course Settings',
                      [
                        _buildSemesterDropdownMenu(),
                        _buildTextField(
                          controller: _sessionsController,
                          label: 'Number of Sessions',
                          hint: 'E.g.: 10, 15, 20',
                          keyboardType: TextInputType.number,
                          errorText: _sessionsError,
                          validator: (value) {
                            // UI validation: Only check format and empty - business rules in Controller
                            if (value == null || value.isEmpty) {
                              return 'Please enter number of sessions';
                            }
                            final sessions = int.tryParse(value);
                            if (sessions == null) {
                              return 'Please enter a valid number';
                            }
                            return null;
                          },
                        ),
                      ],
                    ),

                    SizedBox(
                      width: double.infinity,
                      height: 56,
                      child: ElevatedButton.icon(
                        onPressed: isLoading ? null : _createCourse,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.green,
                          foregroundColor: Colors.white,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          disabledBackgroundColor: Colors.grey,
                        ),
                        icon: isLoading
                            ? const SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  valueColor: AlwaysStoppedAnimation<Color>(
                                    Colors.white,
                                  ),
                                ),
                              )
                            : const Icon(Icons.add, size: 24),
                        label: Text(
                          isLoading ? 'Creating...' : 'Create Course',
                          style: const TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ),

                    const SizedBox(height: 16),

                    SizedBox(
                      width: double.infinity,
                      height: 56,
                      child: OutlinedButton.icon(
                        onPressed: isLoading ? null : _handleCancel,
                        style: OutlinedButton.styleFrom(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          side: const BorderSide(color: Colors.red),
                        ),
                        icon: const Icon(Icons.close,
                            size: 24, color: Colors.red),
                        label: const Text(
                          'Cancel',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
  }

  @override
  void dispose() {
    _courseCodeController.dispose();
    _courseNameController.dispose();
    _descriptionController.dispose();
    _semesterController.dispose();
    _sessionsController.dispose();
    super.dispose();
  }
}
